### ISSUE TITLE
História: Criação de Treinos Personalizados

### ISSUE THREAD

**Issue by LuizGuilhermeNascimento** [VLV-subgrupo/o2t#16]
Eu, como atleta, desejo poder criar e personalizar planos de treinamento com base nas metas e necessidades pessoais.

**Comment by vitto-wu** [comment]
- Log Page update #47 
Tela 'Workout Log' para criação, gerenciamento e edição de treinos personalizados baseado nas metas e necessidades pessoais, com a possibilidade de incluir  data do treino e tags associadas.

**Comment by vitorpaziam** [comment]
- Adição dos Serviços e Endpoints para gerenciamento de Treinos #51 
- Gerenciamento de Labels dos Treinos #46
