### ISSUE TITLE
História: Acompanhamento de treinos futuros

### ISSUE THREAD

**Issue by LuizGuilhermeNascimento** [VLV-subgrupo/o2t#17]
Eu, como atleta, desejo poder visualizar e editar planos de treinos futuros previamente cadastrados.

**Comment by vitorpaziam** [comment]
Mesmo PRs apresentados na outra história:
- Log Page update #47 
- Adição dos Serviços e Endpoints para gerenciamento de Treinos #51 
- Gerenciamento de Labels dos Treinos #46
