### ISSUE TITLE
História: Cadastro de Métricas Diárias

### ISSUE THREAD

**Issue by luiz-fll** [VLV-subgrupo/o2t#20]
Eu, como atleta, desejo poder registrar minhas métricas de saúde diárias, como peso, nível de hidratação, sono e o gasto calórico no exercícios, para monitorar meu bem-estar ao longo do tempo.

**Comment by vitorpaziam** [comment]
As PRs associadas a essa história são:
- Frontend:
    - #64 
    - #66 
- Backend:
    - #56
