### ISSUE TITLE
Criação do prejeto Next.js  e protótipo de tela

### ISSUE THREAD

**Issue by vitorpaziam** [VLV-subgrupo/o2t#3]
- [x] Criação do Projeto Next.js
- [x] Protótipo das telas no Figma

**Comment by vitto-wu** [comment]
Protótipo de tela e fluxo de usuário no [Figma](https://www.figma.com/file/50gTVkq519X2AJez5Q1l2w/MC656?type=design&mode=design&t=vYNA00qA8Do9Dr4l-1)
