### ISSUE TITLE
teste frontend

### ISSUE THREAD

**Issue by vitto-wu** [VLV-subgrupo/o2t#48]
teste do componente 'InputNum' utilizando os critérios de particionamento em classes de equivalências e análise de valor limite;

**Comment by luiz-fll** [comment]
Local do Arquivo: [`./frontend/app/__tests__/inputTest.tsx`](https://github.com/VLV-subgrupo/o2t/blob/develop/frontend/app/__tests__/inputTest.tsx)
Pull Request: #49 Add Input Tests
Evidência de execução de testes: comando "npm run test"
![image](https://github.com/VLV-subgrupo/o2t/assets/127907106/62f7867e-02c4-4506-8852-113568eb1a8b)

**Comment by vitto-wu** [comment]
Critérios de Teste Adotados:
- Particionamento em classes de equivalência:
  - Teste de renderização de componente
  - Teste de renderização de componente com valor valido
- Análise de Valor Limite
  - Teste de análise de limite de uma entrada numérica de 0 a 9
  - Teste de uma entrada não numérica
  - Teste da entrada 'Backspace'
