### ISSUE TITLE
Integrar frontend com a API

### ISSUE THREAD

**Issue by luiz-fll** [VLV-subgrupo/o2t#55]
O frontend deve ser capaz de consumir a API fornecida pelo backend, fazendo requests e recebendo responses do servidor.

- [x] Criar Handlers para cadastro, login, alteração e remoção de usuários
- [x] Criar Handlers para treinos
- [x] Criar Handlers para métricas
- [x] Criar Handlers para labels

**Comment by vitorpaziam** [comment]
PR associada: #59
